# Generated by Django 5.2.6 on 2025-09-22 11:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_tender_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='seat_count',
        ),
        migrations.RemoveField(
            model_name='team',
            name='seats_used',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='status',
        ),
        migrations.AlterField(
            model_name='team',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], default='free', max_length=20),
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
