# Generated by Django 5.2.6 on 2025-09-22 23:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_remove_team_seat_count_remove_team_seats_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('tax_clearance', 'Tax Clearance Certificate'), ('company_registration', 'Company Registration'), ('bbbee_certificate', 'B-BBEE Certificate'), ('cidb_registration', 'CIDB Registration'), ('letter_of_good_standing', 'Letter of Good Standing'), ('financial_statements', 'Financial Statements'), ('other', 'Other')], max_length=50)),
                ('document_file', models.FileField(upload_to='company_documents/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_documents', to='tenders.team')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
